package com.r0adkll.deckbuilder.util

import android.util.ArrayMap
import com.r0adkll.deckbuilder.arch.domain.features.cards.model.Effect
import com.r0adkll.deckbuilder.arch.domain.features.cards.model.PokemonCard
import com.r0adkll.deckbuilder.arch.domain.features.cards.model.StackedPokemonCard
import io.pokemontcg.model.Type


object CardUtils {
    val CARDS: Array<String> = arrayOf(
            "https://images.pokemontcg.io/sm6/19.png",
            "https://images.pokemontcg.io/sm4/66.png",
            "https://images.pokemontcg.io/sm6/2.png",
            "https://images.pokemontcg.io/sm5/155.png",
            "https://images.pokemontcg.io/sm5/140.png",
            "https://images.pokemontcg.io/sm6/73.png",
            "https://images.pokemontcg.io/sm6/115.png",
            "https://images.pokemontcg.io/sm7/16.png",
            "https://images.pokemontcg.io/sm5/15.png",
            "https://images.pokemontcg.io/sm35/44.png",
            "https://images.pokemontcg.io/sm6/90.png",
            "https://images.pokemontcg.io/sm4/97.png",
            "https://images.pokemontcg.io/sm5/13.png",
            "https://images.pokemontcg.io/sm7/88.png",
            "https://images.pokemontcg.io/sm7/124.png",
            "https://images.pokemontcg.io/sm35/56.png",
            "https://images.pokemontcg.io/sm4/33.png",
            "https://images.pokemontcg.io/sm7/25.png",
            "https://images.pokemontcg.io/sm5/60.png",
            "https://images.pokemontcg.io/sm6/106.png",
            "https://images.pokemontcg.io/sm5/112.png",
            "https://images.pokemontcg.io/sm5/154.png",
            "https://images.pokemontcg.io/sm6/59.png",
            "https://images.pokemontcg.io/sm4/116.png",
            "https://images.pokemontcg.io/sm7/53.png",
            "https://images.pokemontcg.io/sm5/26.png",
            "https://images.pokemontcg.io/sm5/66.png",
            "https://images.pokemontcg.io/sm5/30.png",
            "https://images.pokemontcg.io/sm7/3.png",
            "https://images.pokemontcg.io/sm6/52.png",
            "https://images.pokemontcg.io/sm6/63.png",
            "https://images.pokemontcg.io/sm5/37.png",
            "https://images.pokemontcg.io/sm35/70.png",
            "https://images.pokemontcg.io/sm5/50.png",
            "https://images.pokemontcg.io/sm4/10.png",
            "https://images.pokemontcg.io/sm35/75.png",
            "https://images.pokemontcg.io/sm7/17.png",
            "https://images.pokemontcg.io/sm5/151.png",
            "https://images.pokemontcg.io/sm4/51.png",
            "https://images.pokemontcg.io/sm7/156.png",
            "https://images.pokemontcg.io/sm7/73.png",
            "https://images.pokemontcg.io/sm5/41.png",
            "https://images.pokemontcg.io/sm4/39.png",
            "https://images.pokemontcg.io/sm35/28.png",
            "https://images.pokemontcg.io/sm4/4.png",
            "https://images.pokemontcg.io/sm4/92.png",
            "https://images.pokemontcg.io/sm7/129.png",
            "https://images.pokemontcg.io/sm7/158.png",
            "https://images.pokemontcg.io/sm6/66.png",
            "https://images.pokemontcg.io/sm6/13.png",
            "https://images.pokemontcg.io/sm5/153.png",
            "https://images.pokemontcg.io/sm6/17.png",
            "https://images.pokemontcg.io/sm6/18.png",
            "https://images.pokemontcg.io/sm7/91.png",
            "https://images.pokemontcg.io/sm7/20.png",
            "https://images.pokemontcg.io/sm6/12.png",
            "https://images.pokemontcg.io/sm6/124.png",
            "https://images.pokemontcg.io/sm4/109.png",
            "https://images.pokemontcg.io/sm35/5.png",
            "https://images.pokemontcg.io/sm35/24.png",
            "https://images.pokemontcg.io/sm7/110.png",
            "https://images.pokemontcg.io/sm5/39.png",
            "https://images.pokemontcg.io/sm4/79.png",
            "https://images.pokemontcg.io/sm6/31.png",
            "https://images.pokemontcg.io/sm5/40.png",
            "https://images.pokemontcg.io/sm4/19.png",
            "https://images.pokemontcg.io/sm4/67.png",
            "https://images.pokemontcg.io/sm7/160.png",
            "https://images.pokemontcg.io/sm5/98.png",
            "https://images.pokemontcg.io/sm7/114.png",
            "https://images.pokemontcg.io/sm7/138.png",
            "https://images.pokemontcg.io/sm5/103.png",
            "https://images.pokemontcg.io/sm5/69.png",
            "https://images.pokemontcg.io/sm6/37.png",
            "https://images.pokemontcg.io/sm5/123.png",
            "https://images.pokemontcg.io/sm35/69.png",
            "https://images.pokemontcg.io/sm35/52.png",
            "https://images.pokemontcg.io/sm7/33.png",
            "https://images.pokemontcg.io/sm4/70.png",
            "https://images.pokemontcg.io/sm6/100.png",
            "https://images.pokemontcg.io/sm5/68.png",
            "https://images.pokemontcg.io/sm7/154.png",
            "https://images.pokemontcg.io/sm5/24.png",
            "https://images.pokemontcg.io/sm6/72.png",
            "https://images.pokemontcg.io/sm4/22.png",
            "https://images.pokemontcg.io/sm7/102.png",
            "https://images.pokemontcg.io/sm6/125.png",
            "https://images.pokemontcg.io/sm5/133.png",
            "https://images.pokemontcg.io/sm5/22.png",
            "https://images.pokemontcg.io/sm5/3.png",
            "https://images.pokemontcg.io/sm6/62.png",
            "https://images.pokemontcg.io/sm5/67.png",
            "https://images.pokemontcg.io/sm6/39.png",
            "https://images.pokemontcg.io/sm35/45.png",
            "https://images.pokemontcg.io/sm35/16.png",
            "https://images.pokemontcg.io/sm4/78.png",
            "https://images.pokemontcg.io/sm6/32.png",
            "https://images.pokemontcg.io/sm35/23.png",
            "https://images.pokemontcg.io/sm6/1.png",
            "https://images.pokemontcg.io/sm6/110.png",
            "https://images.pokemontcg.io/sm7/118.png",
            "https://images.pokemontcg.io/sm7/79.png",
            "https://images.pokemontcg.io/sm4/117.png",
            "https://images.pokemontcg.io/sm5/25.png",
            "https://images.pokemontcg.io/sm4/112.png",
            "https://images.pokemontcg.io/sm5/130.png",
            "https://images.pokemontcg.io/sm4/54.png",
            "https://images.pokemontcg.io/sm5/92.png",
            "https://images.pokemontcg.io/sm5/86.png",
            "https://images.pokemontcg.io/sm5/126.png",
            "https://images.pokemontcg.io/sm5/135.png",
            "https://images.pokemontcg.io/sm6/123.png",
            "https://images.pokemontcg.io/sm5/132.png",
            "https://images.pokemontcg.io/sm5/149.png",
            "https://images.pokemontcg.io/sm5/27.png",
            "https://images.pokemontcg.io/sm6/70.png",
            "https://images.pokemontcg.io/sm6/10.png",
            "https://images.pokemontcg.io/sm7/22.png",
            "https://images.pokemontcg.io/sm6/107.png",
            "https://images.pokemontcg.io/sm5/56.png",
            "https://images.pokemontcg.io/sm4/29.png",
            "https://images.pokemontcg.io/sm6/61.png",
            "https://images.pokemontcg.io/sm4/88.png",
            "https://images.pokemontcg.io/sm35/76.png",
            "https://images.pokemontcg.io/sm4/20.png",
            "https://images.pokemontcg.io/sm4/107.png",
            "https://images.pokemontcg.io/sm5/152.png",
            "https://images.pokemontcg.io/sm4/72.png",
            "https://images.pokemontcg.io/sm5/147.png",
            "https://images.pokemontcg.io/sm7/8.png",
            "https://images.pokemontcg.io/sm7/122.png",
            "https://images.pokemontcg.io/sm35/6.png",
            "https://images.pokemontcg.io/sm4/84.png",
            "https://images.pokemontcg.io/sm5/71.png",
            "https://images.pokemontcg.io/sm5/95.png",
            "https://images.pokemontcg.io/sm35/12.png",
            "https://images.pokemontcg.io/sm7/132.png",
            "https://images.pokemontcg.io/sm5/53.png",
            "https://images.pokemontcg.io/sm5/100.png",
            "https://images.pokemontcg.io/sm4/28.png",
            "https://images.pokemontcg.io/sm35/13.png",
            "https://images.pokemontcg.io/sm5/5.png",
            "https://images.pokemontcg.io/sm35/55.png",
            "https://images.pokemontcg.io/sm5/33.png",
            "https://images.pokemontcg.io/sm7/21.png",
            "https://images.pokemontcg.io/sm35/60.png",
            "https://images.pokemontcg.io/sm5/144.png",
            "https://images.pokemontcg.io/sm4/42.png",
            "https://images.pokemontcg.io/sm4/101.png",
            "https://images.pokemontcg.io/sm35/77.png",
            "https://images.pokemontcg.io/sm5/61.png",
            "https://images.pokemontcg.io/sm7/19.png",
            "https://images.pokemontcg.io/sm7/133.png",
            "https://images.pokemontcg.io/sm4/64.png",
            "https://images.pokemontcg.io/sm35/66.png",
            "https://images.pokemontcg.io/sm7/11.png",
            "https://images.pokemontcg.io/sm4/53.png",
            "https://images.pokemontcg.io/sm4/8.png",
            "https://images.pokemontcg.io/sm5/138.png",
            "https://images.pokemontcg.io/sm35/72.png",
            "https://images.pokemontcg.io/sm7/148.png",
            "https://images.pokemontcg.io/sm7/63.png",
            "https://images.pokemontcg.io/sm7/136.png",
            "https://images.pokemontcg.io/sm7/74.png",
            "https://images.pokemontcg.io/sm7/76.png",
            "https://images.pokemontcg.io/sm6/93.png",
            "https://images.pokemontcg.io/sm7/7.png",
            "https://images.pokemontcg.io/sm5/106.png",
            "https://images.pokemontcg.io/sm6/33.png",
            "https://images.pokemontcg.io/sm4/63.png",
            "https://images.pokemontcg.io/sm7/14.png",
            "https://images.pokemontcg.io/sm6/87.png",
            "https://images.pokemontcg.io/sm4/5.png",
            "https://images.pokemontcg.io/sm5/141.png",
            "https://images.pokemontcg.io/sm4/77.png",
            "https://images.pokemontcg.io/sm7/89.png",
            "https://images.pokemontcg.io/sm6/22.png",
            "https://images.pokemontcg.io/sm5/7.png",
            "https://images.pokemontcg.io/sm7/36.png",
            "https://images.pokemontcg.io/sm7/67.png",
            "https://images.pokemontcg.io/sm5/102.png",
            "https://images.pokemontcg.io/sm6/122.png",
            "https://images.pokemontcg.io/sm7/40.png",
            "https://images.pokemontcg.io/sm5/121.png",
            "https://images.pokemontcg.io/sm5/4.png",
            "https://images.pokemontcg.io/sm6/82.png",
            "https://images.pokemontcg.io/sm7/140.png",
            "https://images.pokemontcg.io/sm4/56.png",
            "https://images.pokemontcg.io/sm6/69.png",
            "https://images.pokemontcg.io/sm5/10.png",
            "https://images.pokemontcg.io/sm7/85.png",
            "https://images.pokemontcg.io/sm4/81.png",
            "https://images.pokemontcg.io/sm5/150.png",
            "https://images.pokemontcg.io/sm5/109.png",
            "https://images.pokemontcg.io/sm5/43.png",
            "https://images.pokemontcg.io/sm6/67.png",
            "https://images.pokemontcg.io/sm5/74.png",
            "https://images.pokemontcg.io/sm7/149.png",
            "https://images.pokemontcg.io/sm7/109.png",
            "https://images.pokemontcg.io/sm5/70.png",
            "https://images.pokemontcg.io/sm4/91.png",
            "https://images.pokemontcg.io/sm4/47.png",
            "https://images.pokemontcg.io/sm6/97.png",
            "https://images.pokemontcg.io/sm35/30.png",
            "https://images.pokemontcg.io/sm6/77.png",
            "https://images.pokemontcg.io/sm7/90.png",
            "https://images.pokemontcg.io/sm5/125.png",
            "https://images.pokemontcg.io/sm5/81.png",
            "https://images.pokemontcg.io/sm5/1.png",
            "https://images.pokemontcg.io/sm7/61.png",
            "https://images.pokemontcg.io/sm7/165.png",
            "https://images.pokemontcg.io/sm7/12.png",
            "https://images.pokemontcg.io/sm5/127.png",
            "https://images.pokemontcg.io/sm5/31.png",
            "https://images.pokemontcg.io/sm7/142.png",
            "https://images.pokemontcg.io/sm5/76.png",
            "https://images.pokemontcg.io/sm6/104.png",
            "https://images.pokemontcg.io/sm5/114.png",
            "https://images.pokemontcg.io/sm35/32.png",
            "https://images.pokemontcg.io/sm5/96.png",
            "https://images.pokemontcg.io/sm4/71.png",
            "https://images.pokemontcg.io/sm5/136.png",
            "https://images.pokemontcg.io/sm5/128.png",
            "https://images.pokemontcg.io/sm7/115.png",
            "https://images.pokemontcg.io/sm4/118.png",
            "https://images.pokemontcg.io/sm6/96.png",
            "https://images.pokemontcg.io/sm6/21.png",
            "https://images.pokemontcg.io/sm7/62.png",
            "https://images.pokemontcg.io/sm7/65.png",
            "https://images.pokemontcg.io/sm7/48.png",
            "https://images.pokemontcg.io/sm5/57.png",
            "https://images.pokemontcg.io/sm5/111.png",
            "https://images.pokemontcg.io/sm5/110.png",
            "https://images.pokemontcg.io/sm6/79.png",
            "https://images.pokemontcg.io/sm5/104.png",
            "https://images.pokemontcg.io/sm7/121.png",
            "https://images.pokemontcg.io/sm35/33.png",
            "https://images.pokemontcg.io/sm7/9.png",
            "https://images.pokemontcg.io/sm5/105.png",
            "https://images.pokemontcg.io/sm5/14.png",
            "https://images.pokemontcg.io/sm5/115.png",
            "https://images.pokemontcg.io/sm5/83.png",
            "https://images.pokemontcg.io/sm4/95.png",
            "https://images.pokemontcg.io/sm6/130.png",
            "https://images.pokemontcg.io/sm4/86.png",
            "https://images.pokemontcg.io/sm35/51.png",
            "https://images.pokemontcg.io/sm4/69.png",
            "https://images.pokemontcg.io/sm6/51.png",
            "https://images.pokemontcg.io/sm7/167.png",
            "https://images.pokemontcg.io/sm35/48.png",
            "https://images.pokemontcg.io/sm4/104.png",
            "https://images.pokemontcg.io/sm7/2.png",
            "https://images.pokemontcg.io/sm5/122.png",
            "https://images.pokemontcg.io/sm4/80.png",
            "https://images.pokemontcg.io/sm6/60.png",
            "https://images.pokemontcg.io/sm5/9.png",
            "https://images.pokemontcg.io/sm5/80.png",
            "https://images.pokemontcg.io/sm35/67.png",
            "https://images.pokemontcg.io/sm5/54.png",
            "https://images.pokemontcg.io/sm7/93.png",
            "https://images.pokemontcg.io/sm4/111.png",
            "https://images.pokemontcg.io/sm35/54.png",
            "https://images.pokemontcg.io/sm5/34.png",
            "https://images.pokemontcg.io/sm4/121.png",
            "https://images.pokemontcg.io/sm4/40.png",
            "https://images.pokemontcg.io/sm6/55.png",
            "https://images.pokemontcg.io/sm6/25.png",
            "https://images.pokemontcg.io/sm4/99.png",
            "https://images.pokemontcg.io/sm5/47.png",
            "https://images.pokemontcg.io/sm4/124.png",
            "https://images.pokemontcg.io/sm7/86.png",
            "https://images.pokemontcg.io/sm6/74.png",
            "https://images.pokemontcg.io/sm6/71.png",
            "https://images.pokemontcg.io/sm7/71.png",
            "https://images.pokemontcg.io/sm6/24.png",
            "https://images.pokemontcg.io/sm35/57.png",
            "https://images.pokemontcg.io/sm35/61.png",
            "https://images.pokemontcg.io/sm4/46.png",
            "https://images.pokemontcg.io/sm7/75.png",
            "https://images.pokemontcg.io/sm35/39.png",
            "https://images.pokemontcg.io/sm5/79.png",
            "https://images.pokemontcg.io/sm6/41.png",
            "https://images.pokemontcg.io/sm6/6.png",
            "https://images.pokemontcg.io/sm6/38.png",
            "https://images.pokemontcg.io/sm35/35.png",
            "https://images.pokemontcg.io/sm6/53.png",
            "https://images.pokemontcg.io/sm4/98.png",
            "https://images.pokemontcg.io/sm4/90.png",
            "https://images.pokemontcg.io/sm6/23.png",
            "https://images.pokemontcg.io/sm7/81.png",
            "https://images.pokemontcg.io/sm5/91.png",
            "https://images.pokemontcg.io/sm35/37.png",
            "https://images.pokemontcg.io/sm6/121.png",
            "https://images.pokemontcg.io/sm6/78.png",
            "https://images.pokemontcg.io/sm6/91.png",
            "https://images.pokemontcg.io/sm6/40.png",
            "https://images.pokemontcg.io/sm5/116.png",
            "https://images.pokemontcg.io/sm5/2.png",
            "https://images.pokemontcg.io/sm5/72.png",
            "https://images.pokemontcg.io/sm35/3.png",
            "https://images.pokemontcg.io/sm5/28.png",
            "https://images.pokemontcg.io/sm5/156.png",
            "https://images.pokemontcg.io/sm35/65.png",
            "https://images.pokemontcg.io/sm35/1.png",
            "https://images.pokemontcg.io/sm6/64.png",
            "https://images.pokemontcg.io/sm35/7.png",
            "https://images.pokemontcg.io/sm6/111.png",
            "https://images.pokemontcg.io/sm7/66.png",
            "https://images.pokemontcg.io/sm4/114.png",
            "https://images.pokemontcg.io/sm4/16.png",
            "https://images.pokemontcg.io/sm6/15.png",
            "https://images.pokemontcg.io/sm4/12.png",
            "https://images.pokemontcg.io/sm7/23.png",
            "https://images.pokemontcg.io/sm5/90.png",
            "https://images.pokemontcg.io/sm5/143.png",
            "https://images.pokemontcg.io/sm6/83.png",
            "https://images.pokemontcg.io/sm4/45.png",
            "https://images.pokemontcg.io/sm6/16.png",
            "https://images.pokemontcg.io/sm7/38.png",
            "https://images.pokemontcg.io/sm35/43.png",
            "https://images.pokemontcg.io/sm7/26.png",
            "https://images.pokemontcg.io/sm6/127.png",
            "https://images.pokemontcg.io/sm4/14.png",
            "https://images.pokemontcg.io/sm35/64.png",
            "https://images.pokemontcg.io/sm7/68.png",
            "https://images.pokemontcg.io/sm6/56.png",
            "https://images.pokemontcg.io/sm7/166.png",
            "https://images.pokemontcg.io/sm35/22.png",
            "https://images.pokemontcg.io/sm7/18.png",
            "https://images.pokemontcg.io/sm5/12.png",
            "https://images.pokemontcg.io/sm6/84.png",
            "https://images.pokemontcg.io/sm4/76.png",
            "https://images.pokemontcg.io/sm4/34.png",
            "https://images.pokemontcg.io/sm4/25.png",
            "https://images.pokemontcg.io/sm7/34.png",
            "https://images.pokemontcg.io/sm7/37.png",
            "https://images.pokemontcg.io/sm5/88.png",
            "https://images.pokemontcg.io/sm7/168.png",
            "https://images.pokemontcg.io/sm7/30.png",
            "https://images.pokemontcg.io/sm7/108.png",
            "https://images.pokemontcg.io/sm4/62.png",
            "https://images.pokemontcg.io/sm35/73.png",
            "https://images.pokemontcg.io/sm6/3.png",
            "https://images.pokemontcg.io/sm7/153.png",
            "https://images.pokemontcg.io/sm5/94.png",
            "https://images.pokemontcg.io/sm4/37.png",
            "https://images.pokemontcg.io/sm35/2.png",
            "https://images.pokemontcg.io/sm7/35.png",
            "https://images.pokemontcg.io/sm7/113.png",
            "https://images.pokemontcg.io/sm4/59.png",
            "https://images.pokemontcg.io/sm4/103.png",
            "https://images.pokemontcg.io/sm6/54.png",
            "https://images.pokemontcg.io/sm6/27.png",
            "https://images.pokemontcg.io/sm6/44.png",
            "https://images.pokemontcg.io/sm7/27.png",
            "https://images.pokemontcg.io/sm5/120.png",
            "https://images.pokemontcg.io/sm7/44.png",
            "https://images.pokemontcg.io/sm4/3.png",
            "https://images.pokemontcg.io/sm6/99.png",
            "https://images.pokemontcg.io/sm4/63a.png",
            "https://images.pokemontcg.io/sm4/36.png",
            "https://images.pokemontcg.io/sm7/145.png",
            "https://images.pokemontcg.io/sm7/151.png",
            "https://images.pokemontcg.io/sm4/123.png",
            "https://images.pokemontcg.io/sm35/68.png",
            "https://images.pokemontcg.io/sm5/117.png",
            "https://images.pokemontcg.io/sm35/18.png",
            "https://images.pokemontcg.io/sm5/63.png",
            "https://images.pokemontcg.io/sm5/77.png",
            "https://images.pokemontcg.io/sm7/96.png",
            "https://images.pokemontcg.io/sm7/55.png",
            "https://images.pokemontcg.io/sm6/65.png",
            "https://images.pokemontcg.io/sm35/26.png",
            "https://images.pokemontcg.io/sm4/108.png",
            "https://images.pokemontcg.io/sm4/49.png",
            "https://images.pokemontcg.io/sm5/99.png",
            "https://images.pokemontcg.io/sm7/103.png",
            "https://images.pokemontcg.io/sm35/14.png",
            "https://images.pokemontcg.io/sm5/19.png",
            "https://images.pokemontcg.io/sm7/123.png",
            "https://images.pokemontcg.io/sm35/29.png",
            "https://images.pokemontcg.io/sm35/21.png",
            "https://images.pokemontcg.io/sm6/89.png",
            "https://images.pokemontcg.io/sm7/57.png",
            "https://images.pokemontcg.io/sm6/117.png",
            "https://images.pokemontcg.io/sm5/93.png",
            "https://images.pokemontcg.io/sm6/49.png",
            "https://images.pokemontcg.io/sm35/41.png",
            "https://images.pokemontcg.io/sm4/94.png",
            "https://images.pokemontcg.io/sm5/18.png",
            "https://images.pokemontcg.io/sm7/47.png",
            "https://images.pokemontcg.io/sm7/95.png",
            "https://images.pokemontcg.io/sm35/27.png",
            "https://images.pokemontcg.io/sm7/97.png",
            "https://images.pokemontcg.io/sm7/161.png",
            "https://images.pokemontcg.io/sm4/57.png",
            "https://images.pokemontcg.io/sm7/58.png",
            "https://images.pokemontcg.io/sm7/119.png",
            "https://images.pokemontcg.io/sm6/114.png",
            "https://images.pokemontcg.io/sm6/109.png",
            "https://images.pokemontcg.io/sm6/108.png",
            "https://images.pokemontcg.io/sm6/43.png",
            "https://images.pokemontcg.io/sm4/50.png",
            "https://images.pokemontcg.io/sm7/64.png",
            "https://images.pokemontcg.io/sm6/34.png",
            "https://images.pokemontcg.io/sm7/50.png",
            "https://images.pokemontcg.io/sm35/8.png",
            "https://images.pokemontcg.io/sm6/129.png",
            "https://images.pokemontcg.io/sm5/134.png",
            "https://images.pokemontcg.io/sm6/85.png",
            "https://images.pokemontcg.io/sm35/49.png",
            "https://images.pokemontcg.io/sm7/5.png",
            "https://images.pokemontcg.io/sm5/46.png",
            "https://images.pokemontcg.io/sm5/59.png",
            "https://images.pokemontcg.io/sm35/71.png",
            "https://images.pokemontcg.io/sm6/42.png",
            "https://images.pokemontcg.io/sm7/139.png",
            "https://images.pokemontcg.io/sm5/78.png",
            "https://images.pokemontcg.io/sm7/147.png",
            "https://images.pokemontcg.io/sm7/54.png",
            "https://images.pokemontcg.io/sm7/135.png",
            "https://images.pokemontcg.io/sm5/55.png",
            "https://images.pokemontcg.io/sm4/105.png",
            "https://images.pokemontcg.io/sm5/107.png",
            "https://images.pokemontcg.io/sm4/27.png",
            "https://images.pokemontcg.io/sm35/53.png",
            "https://images.pokemontcg.io/sm7/41.png",
            "https://images.pokemontcg.io/sm4/65.png",
            "https://images.pokemontcg.io/sm6/101.png",
            "https://images.pokemontcg.io/sm6/119.png",
            "https://images.pokemontcg.io/sm35/17.png",
            "https://images.pokemontcg.io/sm35/40.png",
            "https://images.pokemontcg.io/sm7/143.png",
            "https://images.pokemontcg.io/sm6/86.png",
            "https://images.pokemontcg.io/sm7/6.png",
            "https://images.pokemontcg.io/sm6/95.png",
            "https://images.pokemontcg.io/sm6/35.png",
            "https://images.pokemontcg.io/sm7/157.png",
            "https://images.pokemontcg.io/sm5/84.png",
            "https://images.pokemontcg.io/sm5/64.png",
            "https://images.pokemontcg.io/sm4/9.png",
            "https://images.pokemontcg.io/sm7/116.png",
            "https://images.pokemontcg.io/sm6/9.png",
            "https://images.pokemontcg.io/sm35/34.png",
            "https://images.pokemontcg.io/sm7/70.png",
            "https://images.pokemontcg.io/sm5/82.png",
            "https://images.pokemontcg.io/sm7/56.png",
            "https://images.pokemontcg.io/sm7/94.png",
            "https://images.pokemontcg.io/sm7/106.png",
            "https://images.pokemontcg.io/sm4/115.png",
            "https://images.pokemontcg.io/sm7/137.png",
            "https://images.pokemontcg.io/sm6/50.png",
            "https://images.pokemontcg.io/sm7/10.png",
            "https://images.pokemontcg.io/sm5/38.png",
            "https://images.pokemontcg.io/sm4/73.png",
            "https://images.pokemontcg.io/sm4/55.png",
            "https://images.pokemontcg.io/sm5/108.png",
            "https://images.pokemontcg.io/sm5/131.png",
            "https://images.pokemontcg.io/sm35/20.png",
            "https://images.pokemontcg.io/sm7/83.png",
            "https://images.pokemontcg.io/sm4/113.png",
            "https://images.pokemontcg.io/sm4/110.png",
            "https://images.pokemontcg.io/sm7/69.png",
            "https://images.pokemontcg.io/sm5/17.png",
            "https://images.pokemontcg.io/sm6/20.png",
            "https://images.pokemontcg.io/sm4/1.png",
            "https://images.pokemontcg.io/sm5/146.png",
            "https://images.pokemontcg.io/sm4/17.png",
            "https://images.pokemontcg.io/sm7/125.png",
            "https://images.pokemontcg.io/sm35/59.png",
            "https://images.pokemontcg.io/sm4/96.png",
            "https://images.pokemontcg.io/sm35/42.png",
            "https://images.pokemontcg.io/sm7/107.png",
            "https://images.pokemontcg.io/sm5/65.png",
            "https://images.pokemontcg.io/sm6/8.png",
            "https://images.pokemontcg.io/sm7/104.png",
            "https://images.pokemontcg.io/sm4/120.png",
            "https://images.pokemontcg.io/sm7/146.png",
            "https://images.pokemontcg.io/sm7/126.png",
            "https://images.pokemontcg.io/sm5/87.png",
            "https://images.pokemontcg.io/sm4/35.png",
            "https://images.pokemontcg.io/sm5/44.png",
            "https://images.pokemontcg.io/sm35/11.png",
            "https://images.pokemontcg.io/sm35/10.png",
            "https://images.pokemontcg.io/sm5/62.png",
            "https://images.pokemontcg.io/sm5/142.png",
            "https://images.pokemontcg.io/sm5/75.png",
            "https://images.pokemontcg.io/sm7/4.png",
            "https://images.pokemontcg.io/sm5/97.png",
            "https://images.pokemontcg.io/sm5/45.png",
            "https://images.pokemontcg.io/sm6/36.png",
            "https://images.pokemontcg.io/sm4/106.png",
            "https://images.pokemontcg.io/sm4/87.png",
            "https://images.pokemontcg.io/sm7/87.png",
            "https://images.pokemontcg.io/sm6/88.png",
            "https://images.pokemontcg.io/sm4/26.png",
            "https://images.pokemontcg.io/sm7/155.png",
            "https://images.pokemontcg.io/sm35/25.png",
            "https://images.pokemontcg.io/sm6/47.png",
            "https://images.pokemontcg.io/sm4/82.png",
            "https://images.pokemontcg.io/sm5/35.png",
            "https://images.pokemontcg.io/sm35/50.png",
            "https://images.pokemontcg.io/sm5/29.png",
            "https://images.pokemontcg.io/sm6/131.png",
            "https://images.pokemontcg.io/sm5/118.png",
            "https://images.pokemontcg.io/sm4/58.png",
            "https://images.pokemontcg.io/sm6/26.png",
            "https://images.pokemontcg.io/sm7/45.png",
            "https://images.pokemontcg.io/sm6/5.png",
            "https://images.pokemontcg.io/sm6/116.png",
            "https://images.pokemontcg.io/sm5/73.png",
            "https://images.pokemontcg.io/sm6/46.png",
            "https://images.pokemontcg.io/sm5/124.png",
            "https://images.pokemontcg.io/sm35/58.png",
            "https://images.pokemontcg.io/sm6/7.png",
            "https://images.pokemontcg.io/sm6/118.png",
            "https://images.pokemontcg.io/sm35/62.png",
            "https://images.pokemontcg.io/sm7/111.png",
            "https://images.pokemontcg.io/sm4/52.png",
            "https://images.pokemontcg.io/sm4/48.png",
            "https://images.pokemontcg.io/sm4/23.png",
            "https://images.pokemontcg.io/sm4/89.png",
            "https://images.pokemontcg.io/sm35/19.png",
            "https://images.pokemontcg.io/sm7/32.png",
            "https://images.pokemontcg.io/sm4/93.png",
            "https://images.pokemontcg.io/sm6/58.png",
            "https://images.pokemontcg.io/sm4/68.png",
            "https://images.pokemontcg.io/sm7/80.png",
            "https://images.pokemontcg.io/sm7/82.png",
            "https://images.pokemontcg.io/sm5/129.png",
            "https://images.pokemontcg.io/sm5/137.png",
            "https://images.pokemontcg.io/sm6/29.png",
            "https://images.pokemontcg.io/sm5/20.png",
            "https://images.pokemontcg.io/sm7/29.png",
            "https://images.pokemontcg.io/sm6/113.png",
            "https://images.pokemontcg.io/sm4/122.png",
            "https://images.pokemontcg.io/sm7/128.png",
            "https://images.pokemontcg.io/sm4/30.png",
            "https://images.pokemontcg.io/sm35/47.png",
            "https://images.pokemontcg.io/sm5/85.png",
            "https://images.pokemontcg.io/sm5/6.png",
            "https://images.pokemontcg.io/sm6/76.png",
            "https://images.pokemontcg.io/sm7/134.png",
            "https://images.pokemontcg.io/sm35/15.png",
            "https://images.pokemontcg.io/sm7/51.png",
            "https://images.pokemontcg.io/sm7/159.png",
            "https://images.pokemontcg.io/sm7/99.png",
            "https://images.pokemontcg.io/sm5/32.png",
            "https://images.pokemontcg.io/sm7/164.png",
            "https://images.pokemontcg.io/sm7/77.png",
            "https://images.pokemontcg.io/sm6/57.png",
            "https://images.pokemontcg.io/sm35/4.png",
            "https://images.pokemontcg.io/sm4/13.png",
            "https://images.pokemontcg.io/sm4/15.png",
            "https://images.pokemontcg.io/sm6/102.png",
            "https://images.pokemontcg.io/sm4/32.png",
            "https://images.pokemontcg.io/sm6/28.png",
            "https://images.pokemontcg.io/sm5/148.png",
            "https://images.pokemontcg.io/sm4/100.png",
            "https://images.pokemontcg.io/sm5/119.png",
            "https://images.pokemontcg.io/sm4/41.png",
            "https://images.pokemontcg.io/sm35/78.png",
            "https://images.pokemontcg.io/sm5/52.png",
            "https://images.pokemontcg.io/sm7/92.png",
            "https://images.pokemontcg.io/sm7/117.png",
            "https://images.pokemontcg.io/sm7/15.png",
            "https://images.pokemontcg.io/sm4/18.png",
            "https://images.pokemontcg.io/sm4/61.png",
            "https://images.pokemontcg.io/sm7/59.png",
            "https://images.pokemontcg.io/sm7/101.png",
            "https://images.pokemontcg.io/sm4/2.png",
            "https://images.pokemontcg.io/sm35/74.png",
            "https://images.pokemontcg.io/sm7/144.png",
            "https://images.pokemontcg.io/sm7/39.png",
            "https://images.pokemontcg.io/sm7/98.png",
            "https://images.pokemontcg.io/sm7/60.png",
            "https://images.pokemontcg.io/sm6/103.png",
            "https://images.pokemontcg.io/sm4/74.png",
            "https://images.pokemontcg.io/sm7/72.png",
            "https://images.pokemontcg.io/sm7/105.png",
            "https://images.pokemontcg.io/sm5/58.png",
            "https://images.pokemontcg.io/sm6/80.png",
            "https://images.pokemontcg.io/sm5/8.png",
            "https://images.pokemontcg.io/sm7/43.png",
            "https://images.pokemontcg.io/sm5/89.png",
            "https://images.pokemontcg.io/sm4/24.png",
            "https://images.pokemontcg.io/sm7/150.png",
            "https://images.pokemontcg.io/sm6/126.png",
            "https://images.pokemontcg.io/sm7/120.png",
            "https://images.pokemontcg.io/sm35/31.png",
            "https://images.pokemontcg.io/sm7/130.png",
            "https://images.pokemontcg.io/sm5/48.png",
            "https://images.pokemontcg.io/sm35/36.png",
            "https://images.pokemontcg.io/sm4/11.png",
            "https://images.pokemontcg.io/sm7/13.png",
            "https://images.pokemontcg.io/sm4/60.png",
            "https://images.pokemontcg.io/sm4/102.png",
            "https://images.pokemontcg.io/sm6/112.png",
            "https://images.pokemontcg.io/sm4/6.png",
            "https://images.pokemontcg.io/sm35/46.png",
            "https://images.pokemontcg.io/sm7/131.png",
            "https://images.pokemontcg.io/sm5/145.png",
            "https://images.pokemontcg.io/sm6/81.png",
            "https://images.pokemontcg.io/sm6/75.png",
            "https://images.pokemontcg.io/sm7/42.png",
            "https://images.pokemontcg.io/sm7/24.png",
            "https://images.pokemontcg.io/sm4/38.png",
            "https://images.pokemontcg.io/sm5/21.png",
            "https://images.pokemontcg.io/sm4/43.png",
            "https://images.pokemontcg.io/sm6/94.png",
            "https://images.pokemontcg.io/sm6/128.png",
            "https://images.pokemontcg.io/sm7/152.png",
            "https://images.pokemontcg.io/sm6/45.png",
            "https://images.pokemontcg.io/sm5/51.png",
            "https://images.pokemontcg.io/sm7/28.png",
            "https://images.pokemontcg.io/sm5/16.png",
            "https://images.pokemontcg.io/sm35/9.png",
            "https://images.pokemontcg.io/sm5/113.png",
            "https://images.pokemontcg.io/sm6/92.png",
            "https://images.pokemontcg.io/sm7/78.png",
            "https://images.pokemontcg.io/sm4/21.png",
            "https://images.pokemontcg.io/sm6/68.png",
            "https://images.pokemontcg.io/sm7/1.png",
            "https://images.pokemontcg.io/sm6/30.png",
            "https://images.pokemontcg.io/sm7/100.png",
            "https://images.pokemontcg.io/sm7/49.png",
            "https://images.pokemontcg.io/sm6/120.png",
            "https://images.pokemontcg.io/sm5/139.png",
            "https://images.pokemontcg.io/sm5/23.png",
            "https://images.pokemontcg.io/sm4/7.png",
            "https://images.pokemontcg.io/sm35/63.png",
            "https://images.pokemontcg.io/sm5/49.png",
            "https://images.pokemontcg.io/sm5/36.png",
            "https://images.pokemontcg.io/sm5/42.png",
            "https://images.pokemontcg.io/sm7/84.png",
            "https://images.pokemontcg.io/sm6/11.png",
            "https://images.pokemontcg.io/sm7/162.png",
            "https://images.pokemontcg.io/sm35/38.png",
            "https://images.pokemontcg.io/sm7/112.png",
            "https://images.pokemontcg.io/sm4/31.png",
            "https://images.pokemontcg.io/sm4/119.png",
            "https://images.pokemontcg.io/sm7/163.png",
            "https://images.pokemontcg.io/sm7/31.png",
            "https://images.pokemontcg.io/sm6/105.png",
            "https://images.pokemontcg.io/sm6/48.png",
            "https://images.pokemontcg.io/sm7/141.png",
            "https://images.pokemontcg.io/sm4/83.png",
            "https://images.pokemontcg.io/sm6/4.png",
            "https://images.pokemontcg.io/sm4/85.png",
            "https://images.pokemontcg.io/sm6/14.png",
            "https://images.pokemontcg.io/sm7/52.png",
            "https://images.pokemontcg.io/sm7/127.png",
            "https://images.pokemontcg.io/sm5/101.png",
            "https://images.pokemontcg.io/sm7/46.png",
            "https://images.pokemontcg.io/sm5/11.png",
            "https://images.pokemontcg.io/sm6/98.png",
            "https://images.pokemontcg.io/sm4/44.png",
            "https://images.pokemontcg.io/sm4/75.png"
    )


    fun stackCards(): (List<PokemonCard>) -> List<StackedPokemonCard> {
        return {
            val map = ArrayMap<PokemonCard, Int>(it.size)
            it.forEach { card ->
                val count = map[card] ?: 0
                map[card] = count + 1
            }
            map.map { StackedPokemonCard(it.key, it.value) }
                    .sortedBy { card -> card.card.nationalPokedexNumber }
        }
    }
}


/**
    [C] olorless (Normal, Flying, older cards also Dragon)
    [F] ighting (Fighting, Rock, Ground)
    [L] ightning (Electric)
    [G] rass (Grass, Bug, older cards also Poison)
    [P] sychic (Psychic, Ghost, Poison)
    [M] etal (Steel)
    [W] ater (Water, Ice)
    [D] arkness (Dark)
    Fi[R] e (Fire)
    Drago[N] (Dragon)
    Fair[Y] (Fairy)
 */
fun Type.compact(): String = when(this) {
    Type.COLORLESS -> "C"
    Type.DARKNESS -> "D"
    Type.DRAGON -> "N"
    Type.FAIRY -> "Y"
    Type.FIGHTING -> "F"
    Type.FIRE -> "R"
    Type.GRASS -> "G"
    Type.LIGHTNING -> "L"
    Type.METAL -> "M"
    Type.PSYCHIC -> "P"
    Type.WATER -> "W"
    Type.UNKNOWN -> ""
}


fun String.type(): Type = when(this.toUpperCase()) {
    "C" -> Type.COLORLESS
    "D" -> Type.DARKNESS
    "N" -> Type.DRAGON
    "Y" -> Type.FAIRY
    "F" -> Type.FIGHTING
    "R" -> Type.FIRE
    "G" -> Type.GRASS
    "L" -> Type.LIGHTNING
    "M" -> Type.METAL
    "P" -> Type.PSYCHIC
    "W" -> Type.WATER
    else -> Type.UNKNOWN
}


fun String.deserializeTypes(): List<Type> {
    return this.map {
        it.toString().type()
    }
}


fun List<Type>.compactTypes(): String {
    return this.fold("") { acc, type ->
        acc.plus(type.compact())
    }
}


fun String.deserializeEffects(): List<com.r0adkll.deckbuilder.arch.domain.features.cards.model.Effect> {
    return this.split(",").map {
        val parts = it.replace("[", "").replace("]", "").split("|")
        com.r0adkll.deckbuilder.arch.domain.features.cards.model.Effect(parts[0].type(), parts[1])
    }
}


fun List<Effect>.compactEffects(): String {
    return this.foldIndexed("") { index, acc, effect ->
        val new = acc.plus("[${effect.type.displayName[0].toUpperCase()}|${effect.value}]")
        if (index != this.size - 1) {
            new.plus(",")
        } else {
            new
        }
    }
}

