package com.r0adkll.deckbuilder.util

import android.annotation.SuppressLint
import android.util.ArrayMap
import com.r0adkll.deckbuilder.arch.domain.features.cards.model.Effect
import com.r0adkll.deckbuilder.arch.domain.features.cards.model.PokemonCard
import com.r0adkll.deckbuilder.arch.domain.features.cards.model.StackedPokemonCard
import com.r0adkll.deckbuilder.arch.domain.features.collection.model.CollectionCount
import io.pokemontcg.model.Type


object CardUtils {

    val CARDS: Array<String> = arrayOf(
            "https://images.pokemontcg.io/sm7/162.png",
            "https://images.pokemontcg.io/sm5/33.png",
            "https://images.pokemontcg.io/sm8/122.png",
            "https://images.pokemontcg.io/sm6/31.png",
            "https://images.pokemontcg.io/sm8/49.png",
            "https://images.pokemontcg.io/sm8/34.png",
            "https://images.pokemontcg.io/sm5/53.png",
            "https://images.pokemontcg.io/sm8/30.png",
            "https://images.pokemontcg.io/sm6/132.png",
            "https://images.pokemontcg.io/sm5/40.png",
            "https://images.pokemontcg.io/sm6/51.png",
            "https://images.pokemontcg.io/sm5/129.png",
            "https://images.pokemontcg.io/sm7/128.png",
            "https://images.pokemontcg.io/sm75/21.png",
            "https://images.pokemontcg.io/sm8/128.png",
            "https://images.pokemontcg.io/sm5/18.png",
            "https://images.pokemontcg.io/sm8/24.png",
            "https://images.pokemontcg.io/sm7/168.png",
            "https://images.pokemontcg.io/sm8/206.png",
            "https://images.pokemontcg.io/sm5/154.png",
            "https://images.pokemontcg.io/sm6/75.png",
            "https://images.pokemontcg.io/sm6/16.png",
            "https://images.pokemontcg.io/sm7/102.png",
            "https://images.pokemontcg.io/sm8/59.png",
            "https://images.pokemontcg.io/sm7/133.png",
            "https://images.pokemontcg.io/sm5/10.png",
            "https://images.pokemontcg.io/sm8/222.png",
            "https://images.pokemontcg.io/sm5/38.png",
            "https://images.pokemontcg.io/sm6/123.png",
            "https://images.pokemontcg.io/sm7/97.png",
            "https://images.pokemontcg.io/sm8/102.png",
            "https://images.pokemontcg.io/sm5/97.png",
            "https://images.pokemontcg.io/sm6/121.png",
            "https://images.pokemontcg.io/sm8/2.png",
            "https://images.pokemontcg.io/sm8/189.png",
            "https://images.pokemontcg.io/sm5/50.png",
            "https://images.pokemontcg.io/sm7/41.png",
            "https://images.pokemontcg.io/sm5/79.png",
            "https://images.pokemontcg.io/sm8/26.png",
            "https://images.pokemontcg.io/sm5/14.png",
            "https://images.pokemontcg.io/sm5/114.png",
            "https://images.pokemontcg.io/sm5/43.png",
            "https://images.pokemontcg.io/sm8/164.png",
            "https://images.pokemontcg.io/sm6/107.png",
            "https://images.pokemontcg.io/sm6/124.png",
            "https://images.pokemontcg.io/sm5/55.png",
            "https://images.pokemontcg.io/sm8/69.png",
            "https://images.pokemontcg.io/sm8/74.png",
            "https://images.pokemontcg.io/sm6/74.png",
            "https://images.pokemontcg.io/sm6/144.png",
            "https://images.pokemontcg.io/sm8/196.png",
            "https://images.pokemontcg.io/sm8/151.png",
            "https://images.pokemontcg.io/sm8/89.png",
            "https://images.pokemontcg.io/sm8/75.png",
            "https://images.pokemontcg.io/sm8/130.png",
            "https://images.pokemontcg.io/sm6/5.png",
            "https://images.pokemontcg.io/sm8/50.png",
            "https://images.pokemontcg.io/sm75/68.png",
            "https://images.pokemontcg.io/sm75/30.png",
            "https://images.pokemontcg.io/sm8/39.png",
            "https://images.pokemontcg.io/sm7/141.png",
            "https://images.pokemontcg.io/sm6/15.png",
            "https://images.pokemontcg.io/sm6/65.png",
            "https://images.pokemontcg.io/sm6/105.png",
            "https://images.pokemontcg.io/sm7/66.png",
            "https://images.pokemontcg.io/sm7/176.png",
            "https://images.pokemontcg.io/sm5/86.png",
            "https://images.pokemontcg.io/sm7/112.png",
            "https://images.pokemontcg.io/sm6/60.png",
            "https://images.pokemontcg.io/sm7/40.png",
            "https://images.pokemontcg.io/sm75/36.png",
            "https://images.pokemontcg.io/sm5/112.png",
            "https://images.pokemontcg.io/sm8/185.png",
            "https://images.pokemontcg.io/sm8/60.png",
            "https://images.pokemontcg.io/sm6/62.png",
            "https://images.pokemontcg.io/sm5/89.png",
            "https://images.pokemontcg.io/sm8/65.png",
            "https://images.pokemontcg.io/sm8/114.png",
            "https://images.pokemontcg.io/sm7/70.png",
            "https://images.pokemontcg.io/sm8/154.png",
            "https://images.pokemontcg.io/sm8/159.png",
            "https://images.pokemontcg.io/sm8/205.png",
            "https://images.pokemontcg.io/sm7/93.png",
            "https://images.pokemontcg.io/sm7/39.png",
            "https://images.pokemontcg.io/sm7/4.png",
            "https://images.pokemontcg.io/sm8/55.png",
            "https://images.pokemontcg.io/sm5/140.png",
            "https://images.pokemontcg.io/sm6/42.png",
            "https://images.pokemontcg.io/sm7/91.png",
            "https://images.pokemontcg.io/sm5/84.png",
            "https://images.pokemontcg.io/sm5/5.png",
            "https://images.pokemontcg.io/sm75/12.png",
            "https://images.pokemontcg.io/sm8/20.png",
            "https://images.pokemontcg.io/sm6/36.png",
            "https://images.pokemontcg.io/sm5/95.png",
            "https://images.pokemontcg.io/sm7/127.png",
            "https://images.pokemontcg.io/sm6/133.png",
            "https://images.pokemontcg.io/sm7/58.png",
            "https://images.pokemontcg.io/sm7/100.png",
            "https://images.pokemontcg.io/sm8/200.png",
            "https://images.pokemontcg.io/sm7/156.png",
            "https://images.pokemontcg.io/sm8/36.png",
            "https://images.pokemontcg.io/sm6/69.png",
            "https://images.pokemontcg.io/sm6/38.png",
            "https://images.pokemontcg.io/sm8/166.png",
            "https://images.pokemontcg.io/sm5/103.png",
            "https://images.pokemontcg.io/sm7/111.png",
            "https://images.pokemontcg.io/sm7/75.png",
            "https://images.pokemontcg.io/sm75/23.png",
            "https://images.pokemontcg.io/sm8/29.png",
            "https://images.pokemontcg.io/sm75/32.png",
            "https://images.pokemontcg.io/sm75/10.png",
            "https://images.pokemontcg.io/sm8/25.png",
            "https://images.pokemontcg.io/sm6/139.png",
            "https://images.pokemontcg.io/sm5/45.png",
            "https://images.pokemontcg.io/sm8/193.png",
            "https://images.pokemontcg.io/sm8/58.png",
            "https://images.pokemontcg.io/sm7/69.png",
            "https://images.pokemontcg.io/sm5/66.png",
            "https://images.pokemontcg.io/sm7/80.png",
            "https://images.pokemontcg.io/sm5/155.png",
            "https://images.pokemontcg.io/sm7/33.png",
            "https://images.pokemontcg.io/sm7/67.png",
            "https://images.pokemontcg.io/sm8/82.png",
            "https://images.pokemontcg.io/sm8/141.png",
            "https://images.pokemontcg.io/sm6/79.png",
            "https://images.pokemontcg.io/sm5/37.png",
            "https://images.pokemontcg.io/sm5/168.png",
            "https://images.pokemontcg.io/sm5/16.png",
            "https://images.pokemontcg.io/sm8/64.png",
            "https://images.pokemontcg.io/sm5/68.png",
            "https://images.pokemontcg.io/sm5/2.png",
            "https://images.pokemontcg.io/sm75/17.png",
            "https://images.pokemontcg.io/sm7/178.png",
            "https://images.pokemontcg.io/sm5/147.png",
            "https://images.pokemontcg.io/sm8/56.png",
            "https://images.pokemontcg.io/sm8/190.png",
            "https://images.pokemontcg.io/sm8/120.png",
            "https://images.pokemontcg.io/sm5/74.png",
            "https://images.pokemontcg.io/sm8/86.png",
            "https://images.pokemontcg.io/sm7/98.png",
            "https://images.pokemontcg.io/sm7/172.png",
            "https://images.pokemontcg.io/sm5/109.png",
            "https://images.pokemontcg.io/sm6/100.png",
            "https://images.pokemontcg.io/sm6/117.png",
            "https://images.pokemontcg.io/sm8/67.png",
            "https://images.pokemontcg.io/sm8/81.png",
            "https://images.pokemontcg.io/sm8/53.png",
            "https://images.pokemontcg.io/sm5/32.png",
            "https://images.pokemontcg.io/sm5/42.png",
            "https://images.pokemontcg.io/sm7/46.png",
            "https://images.pokemontcg.io/sm75/8.png",
            "https://images.pokemontcg.io/sm75/37.png",
            "https://images.pokemontcg.io/sm7/182.png",
            "https://images.pokemontcg.io/sm8/186.png",
            "https://images.pokemontcg.io/sm8/118.png",
            "https://images.pokemontcg.io/sm8/70.png",
            "https://images.pokemontcg.io/sm7/179.png",
            "https://images.pokemontcg.io/sm7/17.png",
            "https://images.pokemontcg.io/sm8/208.png",
            "https://images.pokemontcg.io/sm5/80.png",
            "https://images.pokemontcg.io/sm75/53.png",
            "https://images.pokemontcg.io/sm8/106.png",
            "https://images.pokemontcg.io/sm5/160.png",
            "https://images.pokemontcg.io/sm5/121.png",
            "https://images.pokemontcg.io/sm8/226.png",
            "https://images.pokemontcg.io/sm8/194.png",
            "https://images.pokemontcg.io/sm6/125.png",
            "https://images.pokemontcg.io/sm8/1.png",
            "https://images.pokemontcg.io/sm7/173.png",
            "https://images.pokemontcg.io/sm7/89.png",
            "https://images.pokemontcg.io/sm8/83.png",
            "https://images.pokemontcg.io/sm8/33.png",
            "https://images.pokemontcg.io/sm7/152.png",
            "https://images.pokemontcg.io/sm5/93.png",
            "https://images.pokemontcg.io/sm5/90.png",
            "https://images.pokemontcg.io/sm8/97.png",
            "https://images.pokemontcg.io/sm5/17.png",
            "https://images.pokemontcg.io/sm8/140.png",
            "https://images.pokemontcg.io/sm5/113.png",
            "https://images.pokemontcg.io/sm6/87.png",
            "https://images.pokemontcg.io/sm5/85.png",
            "https://images.pokemontcg.io/sm6/103.png",
            "https://images.pokemontcg.io/sm75/56.png",
            "https://images.pokemontcg.io/sm5/142.png",
            "https://images.pokemontcg.io/sm5/116.png",
            "https://images.pokemontcg.io/sm5/60.png",
            "https://images.pokemontcg.io/sm5/4.png",
            "https://images.pokemontcg.io/sm7/157.png",
            "https://images.pokemontcg.io/sm8/16.png",
            "https://images.pokemontcg.io/sm6/140.png",
            "https://images.pokemontcg.io/sm5/9.png",
            "https://images.pokemontcg.io/sm5/162.png",
            "https://images.pokemontcg.io/sm5/15.png",
            "https://images.pokemontcg.io/sm5/73.png",
            "https://images.pokemontcg.io/sm7/76.png",
            "https://images.pokemontcg.io/sm75/70.png",
            "https://images.pokemontcg.io/sm5/132.png",
            "https://images.pokemontcg.io/sm75/65.png",
            "https://images.pokemontcg.io/sm7/129.png",
            "https://images.pokemontcg.io/sm8/137.png",
            "https://images.pokemontcg.io/sm5/52.png",
            "https://images.pokemontcg.io/sm5/7.png",
            "https://images.pokemontcg.io/sm5/35.png",
            "https://images.pokemontcg.io/sm75/58.png",
            "https://images.pokemontcg.io/sm6/41.png",
            "https://images.pokemontcg.io/sm7/115.png",
            "https://images.pokemontcg.io/sm7/86.png",
            "https://images.pokemontcg.io/sm75/14.png",
            "https://images.pokemontcg.io/sm6/109.png",
            "https://images.pokemontcg.io/sm7/109.png",
            "https://images.pokemontcg.io/sm7/50.png",
            "https://images.pokemontcg.io/sm7/57.png",
            "https://images.pokemontcg.io/sm8/21.png",
            "https://images.pokemontcg.io/sm5/22.png",
            "https://images.pokemontcg.io/sm7/85.png",
            "https://images.pokemontcg.io/sm8/12.png",
            "https://images.pokemontcg.io/sm6/134.png",
            "https://images.pokemontcg.io/sm5/65.png",
            "https://images.pokemontcg.io/sm8/177.png",
            "https://images.pokemontcg.io/sm6/126.png",
            "https://images.pokemontcg.io/sm6/44.png",
            "https://images.pokemontcg.io/sm8/223.png",
            "https://images.pokemontcg.io/sm6/13.png",
            "https://images.pokemontcg.io/sm5/20.png",
            "https://images.pokemontcg.io/sm6/83.png",
            "https://images.pokemontcg.io/sm7/103.png",
            "https://images.pokemontcg.io/sm5/57.png",
            "https://images.pokemontcg.io/sm8/232.png",
            "https://images.pokemontcg.io/sm8/144.png",
            "https://images.pokemontcg.io/sm6/96.png",
            "https://images.pokemontcg.io/sm8/187.png",
            "https://images.pokemontcg.io/sm8/22.png",
            "https://images.pokemontcg.io/sm5/149.png",
            "https://images.pokemontcg.io/sm8/63.png",
            "https://images.pokemontcg.io/sm7/110.png",
            "https://images.pokemontcg.io/sm8/158.png",
            "https://images.pokemontcg.io/sm6/129.png",
            "https://images.pokemontcg.io/sm8/43.png",
            "https://images.pokemontcg.io/sm8/3.png",
            "https://images.pokemontcg.io/sm7/3.png",
            "https://images.pokemontcg.io/sm7/30.png",
            "https://images.pokemontcg.io/sm5/150.png",
            "https://images.pokemontcg.io/sm7/27.png",
            "https://images.pokemontcg.io/sm8/146.png",
            "https://images.pokemontcg.io/sm75/46.png",
            "https://images.pokemontcg.io/sm6/131.png",
            "https://images.pokemontcg.io/sm8/71.png",
            "https://images.pokemontcg.io/sm5/26.png",
            "https://images.pokemontcg.io/sm5/165.png",
            "https://images.pokemontcg.io/sm6/48.png",
            "https://images.pokemontcg.io/sm6/130.png",
            "https://images.pokemontcg.io/sm7/125.png",
            "https://images.pokemontcg.io/sm7/51.png",
            "https://images.pokemontcg.io/sm8/172.png",
            "https://images.pokemontcg.io/sm5/30.png",
            "https://images.pokemontcg.io/sm8/15.png",
            "https://images.pokemontcg.io/sm7/155.png",
            "https://images.pokemontcg.io/sm7/166.png",
            "https://images.pokemontcg.io/sm5/58.png",
            "https://images.pokemontcg.io/sm6/106.png",
            "https://images.pokemontcg.io/sm8/147.png",
            "https://images.pokemontcg.io/sm75/9.png",
            "https://images.pokemontcg.io/sm5/75.png",
            "https://images.pokemontcg.io/sm6/80.png",
            "https://images.pokemontcg.io/sm5/104.png",
            "https://images.pokemontcg.io/sm5/34.png",
            "https://images.pokemontcg.io/sm75/38.png",
            "https://images.pokemontcg.io/sm7/83.png",
            "https://images.pokemontcg.io/sm5/92.png",
            "https://images.pokemontcg.io/sm5/130.png",
            "https://images.pokemontcg.io/sm5/135.png",
            "https://images.pokemontcg.io/sm6/28.png",
            "https://images.pokemontcg.io/sm8/192.png",
            "https://images.pokemontcg.io/sm75/45.png",
            "https://images.pokemontcg.io/sm6/45.png",
            "https://images.pokemontcg.io/sm7/121.png",
            "https://images.pokemontcg.io/sm8/107.png",
            "https://images.pokemontcg.io/sm7/26.png",
            "https://images.pokemontcg.io/sm8/162.png",
            "https://images.pokemontcg.io/sm8/88.png",
            "https://images.pokemontcg.io/sm8/179.png",
            "https://images.pokemontcg.io/sm7/92.png",
            "https://images.pokemontcg.io/sm75/48.png",
            "https://images.pokemontcg.io/sm6/120.png",
            "https://images.pokemontcg.io/sm5/19.png",
            "https://images.pokemontcg.io/sm8/46.png",
            "https://images.pokemontcg.io/sm7/37.png",
            "https://images.pokemontcg.io/sm8/32.png",
            "https://images.pokemontcg.io/sm7/106.png",
            "https://images.pokemontcg.io/sm5/94.png",
            "https://images.pokemontcg.io/sm7/95.png",
            "https://images.pokemontcg.io/sm6/57.png",
            "https://images.pokemontcg.io/sm6/71.png",
            "https://images.pokemontcg.io/sm5/98.png",
            "https://images.pokemontcg.io/sm5/134.png",
            "https://images.pokemontcg.io/sm5/87.png",
            "https://images.pokemontcg.io/sm75/66.png",
            "https://images.pokemontcg.io/sm5/23.png",
            "https://images.pokemontcg.io/sm8/157.png",
            "https://images.pokemontcg.io/sm8/27.png",
            "https://images.pokemontcg.io/sm6/30.png",
            "https://images.pokemontcg.io/sm5/166.png",
            "https://images.pokemontcg.io/sm8/203.png",
            "https://images.pokemontcg.io/sm5/47.png",
            "https://images.pokemontcg.io/sm8/72.png",
            "https://images.pokemontcg.io/sm5/56.png",
            "https://images.pokemontcg.io/sm75/28.png",
            "https://images.pokemontcg.io/sm5/41.png",
            "https://images.pokemontcg.io/sm7/82.png",
            "https://images.pokemontcg.io/sm6/111.png",
            "https://images.pokemontcg.io/sm6/94.png",
            "https://images.pokemontcg.io/sm8/80.png",
            "https://images.pokemontcg.io/sm75/7.png",
            "https://images.pokemontcg.io/sm8/119.png",
            "https://images.pokemontcg.io/sm7/158.png",
            "https://images.pokemontcg.io/sm7/42.png",
            "https://images.pokemontcg.io/sm5/131.png",
            "https://images.pokemontcg.io/sm8/93.png",
            "https://images.pokemontcg.io/sm6/1.png",
            "https://images.pokemontcg.io/sm7/32.png",
            "https://images.pokemontcg.io/sm7/74.png",
            "https://images.pokemontcg.io/sm6/93.png",
            "https://images.pokemontcg.io/sm6/43.png",
            "https://images.pokemontcg.io/sm5/67.png",
            "https://images.pokemontcg.io/sm5/91.png",
            "https://images.pokemontcg.io/sm75/49.png",
            "https://images.pokemontcg.io/sm7/52.png",
            "https://images.pokemontcg.io/sm7/34.png",
            "https://images.pokemontcg.io/sm8/170.png",
            "https://images.pokemontcg.io/sm6/22.png",
            "https://images.pokemontcg.io/sm75/54.png",
            "https://images.pokemontcg.io/sm8/180.png",
            "https://images.pokemontcg.io/sm7/25.png",
            "https://images.pokemontcg.io/sm6/24.png",
            "https://images.pokemontcg.io/sm5/78.png",
            "https://images.pokemontcg.io/sm8/217.png",
            "https://images.pokemontcg.io/sm75/31.png",
            "https://images.pokemontcg.io/sm5/77.png",
            "https://images.pokemontcg.io/sm7/23.png",
            "https://images.pokemontcg.io/sm8/98.png",
            "https://images.pokemontcg.io/sm7/139.png",
            "https://images.pokemontcg.io/sm7/144.png",
            "https://images.pokemontcg.io/sm7/11.png",
            "https://images.pokemontcg.io/sm6/21.png",
            "https://images.pokemontcg.io/sm6/37.png",
            "https://images.pokemontcg.io/sm75/20.png",
            "https://images.pokemontcg.io/sm75/41.png",
            "https://images.pokemontcg.io/sm8/225.png",
            "https://images.pokemontcg.io/sm7/53.png",
            "https://images.pokemontcg.io/sm7/167.png",
            "https://images.pokemontcg.io/sm6/82.png",
            "https://images.pokemontcg.io/sm8/125.png",
            "https://images.pokemontcg.io/sm8/195.png",
            "https://images.pokemontcg.io/sm75/6.png",
            "https://images.pokemontcg.io/sm5/167.png",
            "https://images.pokemontcg.io/sm5/146.png",
            "https://images.pokemontcg.io/sm8/175.png",
            "https://images.pokemontcg.io/sm8/213.png",
            "https://images.pokemontcg.io/sm6/136.png",
            "https://images.pokemontcg.io/sm5/48.png",
            "https://images.pokemontcg.io/sm7/64.png",
            "https://images.pokemontcg.io/sm6/35.png",
            "https://images.pokemontcg.io/sm7/81.png",
            "https://images.pokemontcg.io/sm5/100.png",
            "https://images.pokemontcg.io/sm7/90.png",
            "https://images.pokemontcg.io/sm7/150.png",
            "https://images.pokemontcg.io/sm7/120.png",
            "https://images.pokemontcg.io/sm7/49.png",
            "https://images.pokemontcg.io/sm75/57.png",
            "https://images.pokemontcg.io/sm8/68.png",
            "https://images.pokemontcg.io/sm5/127.png",
            "https://images.pokemontcg.io/sm6/64.png",
            "https://images.pokemontcg.io/sm8/103.png",
            "https://images.pokemontcg.io/sm8/4.png",
            "https://images.pokemontcg.io/sm6/89.png",
            "https://images.pokemontcg.io/sm75/26.png",
            "https://images.pokemontcg.io/sm6/72.png",
            "https://images.pokemontcg.io/sm8/92.png",
            "https://images.pokemontcg.io/sm5/21.png",
            "https://images.pokemontcg.io/sm75/60.png",
            "https://images.pokemontcg.io/sm75/61.png",
            "https://images.pokemontcg.io/sm8/91.png",
            "https://images.pokemontcg.io/sm5/137.png",
            "https://images.pokemontcg.io/sm8/90.png",
            "https://images.pokemontcg.io/sm6/46.png",
            "https://images.pokemontcg.io/sm6/32.png",
            "https://images.pokemontcg.io/sm6/99.png",
            "https://images.pokemontcg.io/sm8/126.png",
            "https://images.pokemontcg.io/sm75/64.png",
            "https://images.pokemontcg.io/sm8/62.png",
            "https://images.pokemontcg.io/sm7/138.png",
            "https://images.pokemontcg.io/sm5/61.png",
            "https://images.pokemontcg.io/sm75/69.png",
            "https://images.pokemontcg.io/sm6/138.png",
            "https://images.pokemontcg.io/sm7/148.png",
            "https://images.pokemontcg.io/sm8/38.png",
            "https://images.pokemontcg.io/sm6/127.png",
            "https://images.pokemontcg.io/sm5/96.png",
            "https://images.pokemontcg.io/sm6/102.png",
            "https://images.pokemontcg.io/sm7/134.png",
            "https://images.pokemontcg.io/sm7/35.png",
            "https://images.pokemontcg.io/sm75/55.png",
            "https://images.pokemontcg.io/sm6/40.png",
            "https://images.pokemontcg.io/sm7/47.png",
            "https://images.pokemontcg.io/sm7/130.png",
            "https://images.pokemontcg.io/sm7/104.png",
            "https://images.pokemontcg.io/sm6/3.png",
            "https://images.pokemontcg.io/sm8/8.png",
            "https://images.pokemontcg.io/sm8/178.png",
            "https://images.pokemontcg.io/sm7/14.png",
            "https://images.pokemontcg.io/sm8/35.png",
            "https://images.pokemontcg.io/sm8/37.png",
            "https://images.pokemontcg.io/sm6/116.png",
            "https://images.pokemontcg.io/sm6/27.png",
            "https://images.pokemontcg.io/sm5/82.png",
            "https://images.pokemontcg.io/sm6/122.png",
            "https://images.pokemontcg.io/sm75/11.png",
            "https://images.pokemontcg.io/sm7/77.png",
            "https://images.pokemontcg.io/sm7/169.png",
            "https://images.pokemontcg.io/sm8/139.png",
            "https://images.pokemontcg.io/sm7/160.png",
            "https://images.pokemontcg.io/sm5/70.png",
            "https://images.pokemontcg.io/sm5/156.png",
            "https://images.pokemontcg.io/sm5/123.png",
            "https://images.pokemontcg.io/sm8/17.png",
            "https://images.pokemontcg.io/sm5/136.png",
            "https://images.pokemontcg.io/sm6/67.png",
            "https://images.pokemontcg.io/sm7/7.png",
            "https://images.pokemontcg.io/sm8/155.png",
            "https://images.pokemontcg.io/sm8/165.png",
            "https://images.pokemontcg.io/sm8/14.png",
            "https://images.pokemontcg.io/sm5/12.png",
            "https://images.pokemontcg.io/sm6/52.png",
            "https://images.pokemontcg.io/sm5/28.png",
            "https://images.pokemontcg.io/sm8/108.png",
            "https://images.pokemontcg.io/sm7/9.png",
            "https://images.pokemontcg.io/sm7/170.png",
            "https://images.pokemontcg.io/sm8/173.png",
            "https://images.pokemontcg.io/sm8/41.png",
            "https://images.pokemontcg.io/sm7/87.png",
            "https://images.pokemontcg.io/sm5/128.png",
            "https://images.pokemontcg.io/sm6/110.png",
            "https://images.pokemontcg.io/sm6/78.png",
            "https://images.pokemontcg.io/sm5/111.png",
            "https://images.pokemontcg.io/sm8/110.png",
            "https://images.pokemontcg.io/sm75/25.png",
            "https://images.pokemontcg.io/sm8/197.png",
            "https://images.pokemontcg.io/sm5/83.png",
            "https://images.pokemontcg.io/sm8/47.png",
            "https://images.pokemontcg.io/sm6/92.png",
            "https://images.pokemontcg.io/sm5/110.png",
            "https://images.pokemontcg.io/sm7/60.png",
            "https://images.pokemontcg.io/sm5/39.png",
            "https://images.pokemontcg.io/sm7/163.png",
            "https://images.pokemontcg.io/sm8/127.png",
            "https://images.pokemontcg.io/sm7/68.png",
            "https://images.pokemontcg.io/sm8/169.png",
            "https://images.pokemontcg.io/sm8/184.png",
            "https://images.pokemontcg.io/sm7/145.png",
            "https://images.pokemontcg.io/sm5/159.png",
            "https://images.pokemontcg.io/sm6/34.png",
            "https://images.pokemontcg.io/sm6/59.png",
            "https://images.pokemontcg.io/sm5/3.png",
            "https://images.pokemontcg.io/sm6/98.png",
            "https://images.pokemontcg.io/sm75/29.png",
            "https://images.pokemontcg.io/sm7/55.png",
            "https://images.pokemontcg.io/sm75/43.png",
            "https://images.pokemontcg.io/sm7/171.png",
            "https://images.pokemontcg.io/sm5/169.png",
            "https://images.pokemontcg.io/sm5/49.png",
            "https://images.pokemontcg.io/sm8/220.png",
            "https://images.pokemontcg.io/sm8/219.png",
            "https://images.pokemontcg.io/sm8/100.png",
            "https://images.pokemontcg.io/sm7/59.png",
            "https://images.pokemontcg.io/sm5/122.png",
            "https://images.pokemontcg.io/sm6/4.png",
            "https://images.pokemontcg.io/sm5/151.png",
            "https://images.pokemontcg.io/sm5/51.png",
            "https://images.pokemontcg.io/sm7/88.png",
            "https://images.pokemontcg.io/sm7/29.png",
            "https://images.pokemontcg.io/sm7/149.png",
            "https://images.pokemontcg.io/sm5/81.png",
            "https://images.pokemontcg.io/sm7/140.png",
            "https://images.pokemontcg.io/sm8/228.png",
            "https://images.pokemontcg.io/sm6/61.png",
            "https://images.pokemontcg.io/sm8/123.png",
            "https://images.pokemontcg.io/sm8/211.png",
            "https://images.pokemontcg.io/sm7/143.png",
            "https://images.pokemontcg.io/sm75/71.png",
            "https://images.pokemontcg.io/sm7/63.png",
            "https://images.pokemontcg.io/sm8/61.png",
            "https://images.pokemontcg.io/sm7/72.png",
            "https://images.pokemontcg.io/sm6/23.png",
            "https://images.pokemontcg.io/sm6/18.png",
            "https://images.pokemontcg.io/sm5/144.png",
            "https://images.pokemontcg.io/sm7/19.png",
            "https://images.pokemontcg.io/sm6/84.png",
            "https://images.pokemontcg.io/sm6/112.png",
            "https://images.pokemontcg.io/sm8/188.png",
            "https://images.pokemontcg.io/sm5/171.png",
            "https://images.pokemontcg.io/sm6/9.png",
            "https://images.pokemontcg.io/sm75/15.png",
            "https://images.pokemontcg.io/sm6/49.png",
            "https://images.pokemontcg.io/sm7/18.png",
            "https://images.pokemontcg.io/sm5/36.png",
            "https://images.pokemontcg.io/sm75/3.png",
            "https://images.pokemontcg.io/sm7/114.png",
            "https://images.pokemontcg.io/sm5/108.png",
            "https://images.pokemontcg.io/sm7/161.png",
            "https://images.pokemontcg.io/sm5/118.png",
            "https://images.pokemontcg.io/sm8/150.png",
            "https://images.pokemontcg.io/sm7/45.png",
            "https://images.pokemontcg.io/sm8/142.png",
            "https://images.pokemontcg.io/sm5/124.png",
            "https://images.pokemontcg.io/sm8/209.png",
            "https://images.pokemontcg.io/sm6/58.png",
            "https://images.pokemontcg.io/sm7/73.png",
            "https://images.pokemontcg.io/sm7/96.png",
            "https://images.pokemontcg.io/sm75/47.png",
            "https://images.pokemontcg.io/sm7/131.png",
            "https://images.pokemontcg.io/sm8/11.png",
            "https://images.pokemontcg.io/sm5/157.png",
            "https://images.pokemontcg.io/sm8/207.png",
            "https://images.pokemontcg.io/sm5/143.png",
            "https://images.pokemontcg.io/sm5/133.png",
            "https://images.pokemontcg.io/sm75/59.png",
            "https://images.pokemontcg.io/sm5/119.png",
            "https://images.pokemontcg.io/sm6/119.png",
            "https://images.pokemontcg.io/sm75/33.png",
            "https://images.pokemontcg.io/sm8/191.png",
            "https://images.pokemontcg.io/sm8/229.png",
            "https://images.pokemontcg.io/sm7/5.png",
            "https://images.pokemontcg.io/sm8/145.png",
            "https://images.pokemontcg.io/sm8/235.png",
            "https://images.pokemontcg.io/sm7/119.png",
            "https://images.pokemontcg.io/sm7/94.png",
            "https://images.pokemontcg.io/sm5/125.png",
            "https://images.pokemontcg.io/sm7/43.png",
            "https://images.pokemontcg.io/sm75/16.png",
            "https://images.pokemontcg.io/sm8/230.png",
            "https://images.pokemontcg.io/sm5/54.png",
            "https://images.pokemontcg.io/sm6/19.png",
            "https://images.pokemontcg.io/sm8/160.png",
            "https://images.pokemontcg.io/sm7/21.png",
            "https://images.pokemontcg.io/sm7/79.png",
            "https://images.pokemontcg.io/sm8/73.png",
            "https://images.pokemontcg.io/sm8/216.png",
            "https://images.pokemontcg.io/sm8/124.png",
            "https://images.pokemontcg.io/sm75/5.png",
            "https://images.pokemontcg.io/sm5/148.png",
            "https://images.pokemontcg.io/sm8/9.png",
            "https://images.pokemontcg.io/sm7/71.png",
            "https://images.pokemontcg.io/sm8/109.png",
            "https://images.pokemontcg.io/sm8/210.png",
            "https://images.pokemontcg.io/sm6/115.png",
            "https://images.pokemontcg.io/sm7/122.png",
            "https://images.pokemontcg.io/sm5/173.png",
            "https://images.pokemontcg.io/sm7/48.png",
            "https://images.pokemontcg.io/sm7/124.png",
            "https://images.pokemontcg.io/sm75/72.png",
            "https://images.pokemontcg.io/sm5/164.png",
            "https://images.pokemontcg.io/sm8/23.png",
            "https://images.pokemontcg.io/sm8/234.png",
            "https://images.pokemontcg.io/sm8/18.png",
            "https://images.pokemontcg.io/sm7/174.png",
            "https://images.pokemontcg.io/sm8/101.png",
            "https://images.pokemontcg.io/sm6/20.png",
            "https://images.pokemontcg.io/sm8/201.png",
            "https://images.pokemontcg.io/sm5/63.png",
            "https://images.pokemontcg.io/sm8/19.png",
            "https://images.pokemontcg.io/sm7/10.png",
            "https://images.pokemontcg.io/sm8/48.png",
            "https://images.pokemontcg.io/sm7/2.png",
            "https://images.pokemontcg.io/sm8/52.png",
            "https://images.pokemontcg.io/sm7/6.png",
            "https://images.pokemontcg.io/sm7/56.png",
            "https://images.pokemontcg.io/sm8/133.png",
            "https://images.pokemontcg.io/sm6/53.png",
            "https://images.pokemontcg.io/sm8/99.png",
            "https://images.pokemontcg.io/sm8/181.png",
            "https://images.pokemontcg.io/sm5/107.png",
            "https://images.pokemontcg.io/sm5/105.png",
            "https://images.pokemontcg.io/sm7/126.png",
            "https://images.pokemontcg.io/sm5/13.png",
            "https://images.pokemontcg.io/sm6/86.png",
            "https://images.pokemontcg.io/sm75/42.png",
            "https://images.pokemontcg.io/sm7/15.png",
            "https://images.pokemontcg.io/sm7/36.png",
            "https://images.pokemontcg.io/sm7/101.png",
            "https://images.pokemontcg.io/sm8/76.png",
            "https://images.pokemontcg.io/sm6/55.png",
            "https://images.pokemontcg.io/sm5/24.png",
            "https://images.pokemontcg.io/sm8/7.png",
            "https://images.pokemontcg.io/sm75/78.png",
            "https://images.pokemontcg.io/sm8/51.png",
            "https://images.pokemontcg.io/sm8/212.png",
            "https://images.pokemontcg.io/sm6/114.png",
            "https://images.pokemontcg.io/sm8/117.png",
            "https://images.pokemontcg.io/sm75/52.png",
            "https://images.pokemontcg.io/sm75/1.png",
            "https://images.pokemontcg.io/sm7/24.png",
            "https://images.pokemontcg.io/sm8/221.png",
            "https://images.pokemontcg.io/sm6/76.png",
            "https://images.pokemontcg.io/sm5/163.png",
            "https://images.pokemontcg.io/sm75/77.png",
            "https://images.pokemontcg.io/sm8/116.png",
            "https://images.pokemontcg.io/sm6/88.png",
            "https://images.pokemontcg.io/sm7/137.png",
            "https://images.pokemontcg.io/sm7/181.png",
            "https://images.pokemontcg.io/sm5/117.png",
            "https://images.pokemontcg.io/sm6/11.png",
            "https://images.pokemontcg.io/sm7/8.png",
            "https://images.pokemontcg.io/sm5/153.png",
            "https://images.pokemontcg.io/sm6/81.png",
            "https://images.pokemontcg.io/sm75/76.png",
            "https://images.pokemontcg.io/sm5/152.png",
            "https://images.pokemontcg.io/sm7/113.png",
            "https://images.pokemontcg.io/sm8/96.png",
            "https://images.pokemontcg.io/sm5/158.png",
            "https://images.pokemontcg.io/sm5/72.png",
            "https://images.pokemontcg.io/sm7/154.png",
            "https://images.pokemontcg.io/sm5/62.png",
            "https://images.pokemontcg.io/sm7/146.png",
            "https://images.pokemontcg.io/sm6/135.png",
            "https://images.pokemontcg.io/sm7/78.png",
            "https://images.pokemontcg.io/sm8/148.png",
            "https://images.pokemontcg.io/sm5/71.png",
            "https://images.pokemontcg.io/sm8/6.png",
            "https://images.pokemontcg.io/sm6/118.png",
            "https://images.pokemontcg.io/sm8/161.png",
            "https://images.pokemontcg.io/sm8/112.png",
            "https://images.pokemontcg.io/sm8/5.png",
            "https://images.pokemontcg.io/sm6/33.png",
            "https://images.pokemontcg.io/sm5/1.png",
            "https://images.pokemontcg.io/sm75/62.png",
            "https://images.pokemontcg.io/sm8/149.png",
            "https://images.pokemontcg.io/sm8/115.png",
            "https://images.pokemontcg.io/sm7/16.png",
            "https://images.pokemontcg.io/sm6/113.png",
            "https://images.pokemontcg.io/sm6/12.png",
            "https://images.pokemontcg.io/sm75/73.png",
            "https://images.pokemontcg.io/sm8/28.png",
            "https://images.pokemontcg.io/sm8/66.png",
            "https://images.pokemontcg.io/sm8/215.png",
            "https://images.pokemontcg.io/sm7/116.png",
            "https://images.pokemontcg.io/sm7/99.png",
            "https://images.pokemontcg.io/sm7/13.png",
            "https://images.pokemontcg.io/sm7/65.png",
            "https://images.pokemontcg.io/sm5/170.png",
            "https://images.pokemontcg.io/sm8/94.png",
            "https://images.pokemontcg.io/sm5/44.png",
            "https://images.pokemontcg.io/sm5/31.png",
            "https://images.pokemontcg.io/sm7/22.png",
            "https://images.pokemontcg.io/sm7/62.png",
            "https://images.pokemontcg.io/sm6/91.png",
            "https://images.pokemontcg.io/sm7/177.png",
            "https://images.pokemontcg.io/sm7/31.png",
            "https://images.pokemontcg.io/sm8/143.png",
            "https://images.pokemontcg.io/sm6/104.png",
            "https://images.pokemontcg.io/sm6/25.png",
            "https://images.pokemontcg.io/sm8/77.png",
            "https://images.pokemontcg.io/sm75/35.png",
            "https://images.pokemontcg.io/sm8/79.png",
            "https://images.pokemontcg.io/sm8/84.png",
            "https://images.pokemontcg.io/sm7/107.png",
            "https://images.pokemontcg.io/sm8/233.png",
            "https://images.pokemontcg.io/sm7/175.png",
            "https://images.pokemontcg.io/sm6/26.png",
            "https://images.pokemontcg.io/sm6/2.png",
            "https://images.pokemontcg.io/sm5/8.png",
            "https://images.pokemontcg.io/sm8/111.png",
            "https://images.pokemontcg.io/sm6/54.png",
            "https://images.pokemontcg.io/sm5/29.png",
            "https://images.pokemontcg.io/sm8/152.png",
            "https://images.pokemontcg.io/sm8/87.png",
            "https://images.pokemontcg.io/sm75/34.png",
            "https://images.pokemontcg.io/sm5/120.png",
            "https://images.pokemontcg.io/sm75/19.png",
            "https://images.pokemontcg.io/sm75/51.png",
            "https://images.pokemontcg.io/sm6/39.png",
            "https://images.pokemontcg.io/sm6/146.png",
            "https://images.pokemontcg.io/sm8/153.png",
            "https://images.pokemontcg.io/sm6/97.png",
            "https://images.pokemontcg.io/sm7/118.png",
            "https://images.pokemontcg.io/sm7/117.png",
            "https://images.pokemontcg.io/sm8/168.png",
            "https://images.pokemontcg.io/sm5/99.png",
            "https://images.pokemontcg.io/sm6/47.png",
            "https://images.pokemontcg.io/sm7/165.png",
            "https://images.pokemontcg.io/sm5/138.png",
            "https://images.pokemontcg.io/sm75/13.png",
            "https://images.pokemontcg.io/sm7/142.png",
            "https://images.pokemontcg.io/sm8/31.png",
            "https://images.pokemontcg.io/sm75/74.png",
            "https://images.pokemontcg.io/sm8/199.png",
            "https://images.pokemontcg.io/sm8/227.png",
            "https://images.pokemontcg.io/sm6/101.png",
            "https://images.pokemontcg.io/sm6/90.png",
            "https://images.pokemontcg.io/sm7/183.png",
            "https://images.pokemontcg.io/sm8/136.png",
            "https://images.pokemontcg.io/sm5/145.png",
            "https://images.pokemontcg.io/sm8/198.png",
            "https://images.pokemontcg.io/sm7/28.png",
            "https://images.pokemontcg.io/sm8/204.png",
            "https://images.pokemontcg.io/sm8/57.png",
            "https://images.pokemontcg.io/sm75/27.png",
            "https://images.pokemontcg.io/sm7/12.png",
            "https://images.pokemontcg.io/sm8/176.png",
            "https://images.pokemontcg.io/sm75/18.png",
            "https://images.pokemontcg.io/sm8/231.png",
            "https://images.pokemontcg.io/sm75/39.png",
            "https://images.pokemontcg.io/sm7/136.png",
            "https://images.pokemontcg.io/sm7/159.png",
            "https://images.pokemontcg.io/sm5/27.png",
            "https://images.pokemontcg.io/sm6/66.png",
            "https://images.pokemontcg.io/sm8/183.png",
            "https://images.pokemontcg.io/sm6/50.png",
            "https://images.pokemontcg.io/sm8/174.png",
            "https://images.pokemontcg.io/sm7/135.png",
            "https://images.pokemontcg.io/sm5/102.png",
            "https://images.pokemontcg.io/sm6/128.png",
            "https://images.pokemontcg.io/sm6/56.png",
            "https://images.pokemontcg.io/sm75/75.png",
            "https://images.pokemontcg.io/sm5/69.png",
            "https://images.pokemontcg.io/sm8/113.png",
            "https://images.pokemontcg.io/sm5/76.png",
            "https://images.pokemontcg.io/sm7/38.png",
            "https://images.pokemontcg.io/sm8/10.png",
            "https://images.pokemontcg.io/sm75/22.png",
            "https://images.pokemontcg.io/sm8/156.png",
            "https://images.pokemontcg.io/sm5/139.png",
            "https://images.pokemontcg.io/sm8/134.png",
            "https://images.pokemontcg.io/sm5/25.png",
            "https://images.pokemontcg.io/sm75/63.png",
            "https://images.pokemontcg.io/sm8/182.png",
            "https://images.pokemontcg.io/sm75/4.png",
            "https://images.pokemontcg.io/sm75/24.png",
            "https://images.pokemontcg.io/sm7/54.png",
            "https://images.pokemontcg.io/sm8/44.png",
            "https://images.pokemontcg.io/sm7/20.png",
            "https://images.pokemontcg.io/sm5/64.png",
            "https://images.pokemontcg.io/sm8/167.png",
            "https://images.pokemontcg.io/sm5/101.png",
            "https://images.pokemontcg.io/sm5/143.png",
            "https://images.pokemontcg.io/sm6/145.png",
            "https://images.pokemontcg.io/sm6/85.png",
            "https://images.pokemontcg.io/sm7/180.png",
            "https://images.pokemontcg.io/sm75/67.png",
            "https://images.pokemontcg.io/sm8/138.png",
            "https://images.pokemontcg.io/sm7/44.png",
            "https://images.pokemontcg.io/sm6/63.png",
            "https://images.pokemontcg.io/sm6/10.png",
            "https://images.pokemontcg.io/sm8/129.png",
            "https://images.pokemontcg.io/sm8/42.png",
            "https://images.pokemontcg.io/sm75/44.png",
            "https://images.pokemontcg.io/sm5/11.png",
            "https://images.pokemontcg.io/sm8/45.png",
            "https://images.pokemontcg.io/sm6/142.png",
            "https://images.pokemontcg.io/sm8/13.png",
            "https://images.pokemontcg.io/sm7/123.png",
            "https://images.pokemontcg.io/sm5/46.png",
            "https://images.pokemontcg.io/sm8/95.png",
            "https://images.pokemontcg.io/sm6/137.png",
            "https://images.pokemontcg.io/sm7/1.png",
            "https://images.pokemontcg.io/sm7/108.png",
            "https://images.pokemontcg.io/sm6/17.png",
            "https://images.pokemontcg.io/sm7/61.png",
            "https://images.pokemontcg.io/sm6/141.png",
            "https://images.pokemontcg.io/sm8/85.png",
            "https://images.pokemontcg.io/sm6/70.png",
            "https://images.pokemontcg.io/sm6/29.png",
            "https://images.pokemontcg.io/sm5/141.png",
            "https://images.pokemontcg.io/sm8/218.png",
            "https://images.pokemontcg.io/sm7/151.png",
            "https://images.pokemontcg.io/sm8/214.png",
            "https://images.pokemontcg.io/sm7/84.png",
            "https://images.pokemontcg.io/sm6/73.png",
            "https://images.pokemontcg.io/sm8/121.png",
            "https://images.pokemontcg.io/sm8/40.png",
            "https://images.pokemontcg.io/sm5/172.png",
            "https://images.pokemontcg.io/sm8/202.png",
            "https://images.pokemontcg.io/sm8/131.png",
            "https://images.pokemontcg.io/sm8/171.png",
            "https://images.pokemontcg.io/sm8/104.png",
            "https://images.pokemontcg.io/sm8/105.png",
            "https://images.pokemontcg.io/sm8/163.png",
            "https://images.pokemontcg.io/sm8/224.png",
            "https://images.pokemontcg.io/sm8/236.png",
            "https://images.pokemontcg.io/sm75/2.png",
            "https://images.pokemontcg.io/sm5/88.png",
            "https://images.pokemontcg.io/sm6/7.png",
            "https://images.pokemontcg.io/sm6/68.png",
            "https://images.pokemontcg.io/sm6/95.png",
            "https://images.pokemontcg.io/sm7/132.png",
            "https://images.pokemontcg.io/sm7/153.png",
            "https://images.pokemontcg.io/sm8/135.png",
            "https://images.pokemontcg.io/sm5/115.png",
            "https://images.pokemontcg.io/sm75/50.png",
            "https://images.pokemontcg.io/sm5/126.png",
            "https://images.pokemontcg.io/sm8/54.png",
            "https://images.pokemontcg.io/sm8/78.png",
            "https://images.pokemontcg.io/sm6/108.png",
            "https://images.pokemontcg.io/sm75/40.png",
            "https://images.pokemontcg.io/sm5/106.png",
            "https://images.pokemontcg.io/sm6/14.png",
            "https://images.pokemontcg.io/sm6/6.png",
            "https://images.pokemontcg.io/sm7/147.png",
            "https://images.pokemontcg.io/sm5/59.png",
            "https://images.pokemontcg.io/sm8/132.png",
            "https://images.pokemontcg.io/sm7/164.png",
            "https://images.pokemontcg.io/sm6/8.png",
            "https://images.pokemontcg.io/sm5/6.png",
            "https://images.pokemontcg.io/sm6/77.png",
            "https://images.pokemontcg.io/sm7/105.png"
    )

    fun stackCards(): (List<PokemonCard>) -> List<StackedPokemonCard> {
        return {
            val map = ArrayMap<PokemonCard, Int>(it.size)
            it.forEach { card ->
                val count = map[card] ?: 0
                map[card] = count + 1
            }
            map.map { StackedPokemonCard(it.key, it.value) }
                    .sortedBy { card -> card.card.nationalPokedexNumber }
        }
    }

    fun stackCards(cards: List<PokemonCard>, collection: List<CollectionCount>): List<StackedPokemonCard> {
        val map = ArrayMap<PokemonCard, Int>(cards.size)
        val collectionMap = ArrayMap<PokemonCard, Int>(cards.size)
        cards.forEach { card ->
            val count = map[card] ?: 0
            map[card] = count + 1
            collectionMap[card] = collection.find { it.id == card.id }?.count ?: 0
        }

        return map.map {
            val collectionCount = collectionMap[it.key] ?: 0
            StackedPokemonCard(it.key, it.value, collectionCount)
        }.sortedBy { card -> card.card.nationalPokedexNumber }
    }
}

fun List<PokemonCard>.stack(): List<StackedPokemonCard> = CardUtils.stackCards().invoke(this)

fun List<PokemonCard>.stack(collection: List<CollectionCount>): List<StackedPokemonCard> = CardUtils.stackCards(this, collection)

fun List<StackedPokemonCard>.unstack(): List<PokemonCard> = this.flatMap { stack ->
    (0 until stack.count).map { stack.card.copy() }
}

/**
    [C] olorless (Normal, Flying, older cards also Dragon)
    [F] ighting (Fighting, Rock, Ground)
    [L] ightning (Electric)
    [G] rass (Grass, Bug, older cards also Poison)
    [P] sychic (Psychic, Ghost, Poison)
    [M] etal (Steel)
    [W] ater (Water, Ice)
    [D] arkness (Dark)
    Fi[R] e (Fire)
    Drago[N] (Dragon)
    Fair[Y] (Fairy)
 */
fun Type.compact(): String = when(this) {
    Type.COLORLESS -> "C"
    Type.DARKNESS -> "D"
    Type.DRAGON -> "N"
    Type.FAIRY -> "Y"
    Type.FIGHTING -> "F"
    Type.FIRE -> "R"
    Type.GRASS -> "G"
    Type.LIGHTNING -> "L"
    Type.METAL -> "M"
    Type.PSYCHIC -> "P"
    Type.WATER -> "W"
    Type.UNKNOWN -> ""
}

@SuppressLint("DefaultLocale")
fun String.type(): Type = when(this.toUpperCase()) {
    "C" -> Type.COLORLESS
    "D" -> Type.DARKNESS
    "N" -> Type.DRAGON
    "Y" -> Type.FAIRY
    "F" -> Type.FIGHTING
    "R" -> Type.FIRE
    "G" -> Type.GRASS
    "L" -> Type.LIGHTNING
    "M" -> Type.METAL
    "P" -> Type.PSYCHIC
    "W" -> Type.WATER
    else -> Type.UNKNOWN
}

fun String.deserializeTypes(): List<Type> {
    return this.map {
        it.toString().type()
    }
}

fun List<Type>.compactTypes(): String {
    return this.fold("") { acc, type ->
        acc.plus(type.compact())
    }
}

fun String.deserializeEffects(): List<Effect> {
    return this.split(",").map {
        val parts = it.replace("[", "").replace("]", "").split("|")
        Effect(parts[0].type(), parts[1])
    }
}

fun List<Effect>.compactEffects(): String {
    return this.foldIndexed("") { index, acc, effect ->
        val new = acc.plus("[${effect.type.displayName[0].toUpperCase()}|${effect.value}]")
        if (index != this.size - 1) {
            new.plus(",")
        } else {
            new
        }
    }
}

fun String.deserializeCardEffects(): List<io.pokemontcg.model.Effect> {
    return this.split(",").map {
        val parts = it.replace("[", "").replace("]", "").split("|")
        io.pokemontcg.model.Effect(parts[0].type(), parts[1])
    }
}

fun List<io.pokemontcg.model.Effect>.compactCardEffects(): String {
    return this.foldIndexed("") { index, acc, effect ->
        val new = acc.plus("[${effect.type.displayName[0].toUpperCase()}|${effect.value}]")
        if (index != this.size - 1) {
            new.plus(",")
        } else {
            new
        }
    }
}

