#!/bin/sh

echo "**** Running Pre-Push Check ****"

git stash -q --keep-index

./gradlew spotlessCheck
./gradlew -P gradle/build-logic spotlessCheck

status=$?

git stash pop -q

echo "**** Pre-Push Check Finished ****"

exit $status
